#!/usr/bin/env bash
# link-kit.sh — Install the kit into ~/.kimi-code/ using SYMLINKS, so that any
# improvement you make on the VPS lives inside the git repo and can be committed.
# Run from the repo: ./kimi/setup/link-kit.sh
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"   # the kimi/ directory of the repo
KIMI_DIR="$HOME/.kimi-code"

echo "Repo: $REPO"
mkdir -p "$KIMI_DIR"

# Backup anything real that we are about to replace with a symlink
STAMP="$(date +%F-%H%M)"
for item in AGENTS.md skills templates; do
  target="$KIMI_DIR/$item"
  if [ -e "$target" ] && [ ! -L "$target" ]; then
    echo "Backing up existing $item -> $item.bak-$STAMP"
    mv "$target" "$target.bak-$STAMP"
  fi
  rm -f "$target"
  ln -s "$REPO/$item" "$target"
  echo "linked: ~/.kimi-code/$item -> kimi/$item"
done

# These stay LOCAL, never symlinked into the repo (machine-specific / sensitive):
#   ~/.kimi-code/agent-memory/  (user-scope agent memories: server map, preferences)
#   ~/.kimi-code/config.toml    (API keys + permission rules, merge manually)
#   ~/.kimi-code/mcp.json       (tokens — generated by mcp-setup.sh, chmod 600)
mkdir -p "$KIMI_DIR/agent-memory"

cat << 'EOF'

Done. Now:
  - Edit skills/templates directly in the repo (or let Kimi edit them there);
    changes are live immediately in ~/.kimi-code/.
  - Merge permissions (once, then keep in sync by hand):
      cat ~/agentic-kit/kimi/config/permissions.toml >> ~/.kimi-code/config.toml
  - Generate MCP config:  ./kimi/setup/mcp-setup.sh
  - Commit improvements:  git add -A && git commit -m "feat(kit): new skill X"
  - Verify in kimi:       /mcp-config   and ask it to list its skills
EOF
